// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spcydtnihwgvziabsnjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwY3lkdG5paHdndnppYWJzbmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTAwNDAsImV4cCI6MjA2NjMyNjA0MH0.iuoKx1UHqzckyz68PH3Ftz0zXhkyatoKygqEw_Qq9tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);