// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxyndujiboulutofwqny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4eW5kdWppYm91bHV0b2Z3cW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwOTQ5OTEsImV4cCI6MjA4MDY3MDk5MX0.zzIXiEbICSAhcIBsfyvkC3iuWLoJ0q4rDzbjP_MCQ34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
